### PR TITLE
feat: binding for Node.JS

### PR DESCRIPTION
**Pull request by shumkov**
- Node.JS binding for Drive
- CI for Node.JS
- Add Rust deps security audit
- Release CI
- Cancel previous CI runs
- Fixed date field encoding
- Fixed non-present indexed field error
- Fixed Merk error if document is not present
- Add `==` operator to support the current
- Fixed contract parsing error
- Introduce query_documents methods
- Handle not binary arrays too
- Disable protocol version verification 
- `orderBy` is not required anymore for equal operator
- Format linting for ci

### CODE REVIEW

**Comment by PastaPastaPasta** [comment]
based on our discussions it seemed like you did this, but if not, please see https://github.com/dashevo/rs-drive/commit/6bbb97455cd5ac044582986956463ab644f14706

**Review by PastaPastaPasta — DISMISSED** [review]
I pushed some fixes, but LGTM

**Review by PastaPastaPasta — DISMISSED** [review]

**Review by QuantumExplorer — DISMISSED** [review]

**Review by QuantumExplorer — APPROVED** [review]

**Review by PastaPastaPasta — APPROVED** [review]

**Review by fominok — COMMENTED** [review]
Despite the fact that it is merged already and I'm late to the party, I would like to pay my respects to everyone involved

**Comment by shumkov** [comment]
And for you as well!

**Pull request merged**
