### PR TITLE
fix: update to GroveDB's API breaking changes

### PR DESCRIPTION
**Pull request by fominok**
This PR resolves errors introduced by recent grovedb refactor

### CODE REVIEW

**Comment by PastaPastaPasta** [comment]
can you please avoid mixing cargo format with changes like this... becomes very annoying to review

**Comment by PastaPastaPasta** [comment]
It seems that you and I worked on the same thing at the same time. I just pushed my fixes to this PR https://github.com/dashevo/rs-drive/pull/22, but I also included a number of valuable changes related to not using vectors when an array does the job. If you could maybe review that PR instead, it might make more sense to move forward with that one

**Comment by fominok** [comment]
> can you please avoid mixing cargo format with changes like this... becomes very annoying to review

Understandable, but maybe we should not have unformatted code in the repo, formatting manually just not to use cargo fmt is very annoying too

**Comment by fominok** [comment]
> It seems that you and I worked on the same thing at the same time. I just pushed my fixes to this PR #22, but I also included a number of valuable changes related to not using vectors when an array does the job. If you could maybe review that PR instead, it might make more sense to move forward with that one

Yeah it makes sense, cannot approve for some reason though

**Review by QuantumExplorer — DISMISSED** [review]

**Comment by QuantumExplorer** [comment]
Do we still need this @PastaPastaPasta @fominok ?

**Comment by fominok** [comment]
I don't think so

**Comment by shumkov** [comment]
@fominok shall we close it?

**Comment by fominok** [comment]
> @fominok shall we close it?

@shumkov yes

**Pull request closed without merging**
